name: Deploy HTML2 to S2

on:
  push:
    branches:
      - main
    paths:
      - 'HTML2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.S2_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy to EC2 S2
      run: |
        rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" ./HTML2/ secureadmin@${{ secrets.S2_PUBLIC_IP }}:/var/www/html/
